### ISSUE TITLE
Error with absolute file path and memoization

### ISSUE THREAD

**Issue by mmower2000** [BIOP/ijp-imagetoatlas#154]
I cannot open the ABBA json files of my registrations. 

When I try to load the state I get an 'error - Index 67, Size 0' then 'Could not load state - Please check the stack trace'

I cannot find a problem with the files and get the same error on another computer. Also this didn't happen to all my states at the same time. Some were fine and others were not, but now they are all give the same error.

**Comment by tgarniera** [comment]
I am having the same problem. A colleague suggested I may have moved the file. I can't remember if I did and if I did then I don't know the previous address. Any solutions?

**Comment by NicoKiaru** [comment]
Hello @mmower2000 and @tgarniera, 

So this issue is clearly the number 1 issue. I'm targeting a release for Feb that should solve most of it.

But for now, you have no other choice but to dig in the saved files for the state, see what's wrong, then fix them with a text editor.

The explanation of what's contained in the saved file has been posted on the forum.

https://forum.image.sc/t/issue-loading-saved-states/75223/7

Basically the `state_sources.json` contains absolute paths to the` _bdvdataset_0.xml` file which itself contains absolute paths linking the qupath project files AND the image files. The qupath project files contains absolute paths to the image files.

All paths need to be correct.

What could have gone wrong:
- moving the image files
- moving the qupath project file
- moving the abba state file
- changing drive letter (D to E for instance)
- renaming a folder containing one of these files above
- using ABBA on different OSes

Additionally, you should not change the number of entries in the QuPath project AFTER it has been used by abba.

Please backup your state files, and try to fix the paths with a text editor (notepad++ advised on windows).

If you can't manage, please share all the state files and qpproj file here, I'll try to look at them and tell you what's the issue.

Related issues on the forum:

- https://forum.image.sc/t/issue-loading-saved-states/75223
- https://forum.image.sc/t/help-for-abba-in-fiji-could-not-load-saved-state/71477/7
- https://forum.image.sc/t/help-for-abba-in-fiji-load-and-save-state/63427/2

**Comment by mmower2000** [comment]
Hi there,

Thanks for getting back to me. I did find these forums which helped but
sadly I could not completely recover the files. I have instead started a
new registration but with being careful with my directories.

I do have a question about how I am supposed to change the location of
these files, for instance upload all the QuPath and ABBA files to a cloud.
Would I need to go through each file in textedit and alter the directory
path? If so, which ones would I do this in, or is there a simpler/quicker
way?

Also, I am trying to import my new registrations from ABBA into QuPath but
I'm receiving the error message shown below. I have installed the
extensions and have downloaded the
GitHub net/imglib2/realtransform/RealTransform files (though can't
find instructions for what to do after downloading), but still get this
error. Have you seen this before?

INFO: Trying to load project
/Users/mattmower/Documents/UCL/1.2_QuP/project.qpproj
ERROR: QuPath exception: net/imglib2/realtransform/RealTransform
java.lang.NoClassDefFoundError: net/imglib2/realtransform/RealTransform

Thanks for the help,

Best wishes,

Matthew

**Comment by NicoKiaru** [comment]
> I do have a question about how I am supposed to change the location of these files, for instance upload all the QuPath and ABBA files to a cloud. Would I need to go through each file in textedit and alter the directory path? If so, which ones would I do this in, or is there a simpler/quicker way?

I think you will need the next release for that to become possible... There's no simpler way currently.

> Also, I am trying to import my new registrations from ABBA into QuPath but
I'm receiving the error message shown below. I have installed the
extensions and have downloaded the
GitHub net/imglib2/realtransform/RealTransform files (though can't
find instructions for what to do after downloading), but still get this
error. Have you seen this before?

Maybe the extension is not properly installed. If you go to Extensions > Installed extensions, do you see Warpy 0.2.0 and ABBA 0.1.4 ?

![image](https://user-images.githubusercontent.com/20223054/213396536-7a96c6d6-12b0-4e61-a710-d81cd8e750d4.png)

In your qupath extension folder, you should see all these files:
![image](https://user-images.githubusercontent.com/20223054/213408874-169115d8-f1d5-4be9-935b-fefcbd8d8358.png)

**Comment by mmower2000** [comment]
Hi Nicholas,

Okay thanks for letting me know. Would you be able to please let me know
every file which would need changing. So the '_bdvdataset_0.xml',
'_sources.json' 'project.qpproj'. Is it just these three files? How about
the hidden files in the original '.tif' image folder?

Also, you were correct about the installation, thank you! However, when I
try use the ABBA extension i now get the error below despite none of my
files changing places, if you have any ideas, it would be greatly
appreciated.

ERROR: QuPath exception: Cannot invoke
"qupath.lib.images.ImageData.getProperty(String)" because "imageData" is
null
java.lang.NullPointerException: Cannot invoke
"qupath.lib.images.ImageData.getProperty(String)" because "imageData" is
null

Thanks again.

Best wishes,

Matthew

**Comment by NicoKiaru** [comment]
> So the '_bdvdataset_0.xml', '_sources.json' 'project.qpproj'. Is it just these three files?

Yes it is these three files

> ERROR: QuPath exception: Cannot invoke
"qupath.lib.images.ImageData.getProperty(String)" because "imageData" is
null
java.lang.NullPointerException: Cannot invoke
"qupath.lib.images.ImageData.getProperty(String)" because "imageData" is
null

Hmm. Have you opened an image (double click on one in the project) ? I suspect your project is opened, but no image is displayed on the right panel.

**Comment by mmower2000** [comment]
Hi Nicholas,

Apologies for the late reply, I was on vacation.

Thank you so much for the help! When I went to try this for the ABBA import
is started working this time, not sure what was happening before but it
looks okay now.

One last thing, do you have any advice about registering the two-photon
mouse brain atlas images with the apline and spline? The images seem to not
register extremely well, with the edges poking around the whole sides and
the centre/split between hemispheres not being correct. I have tried many
combinations of control points and mm but find that only 15,15 is best.

Best wishes,
Matthew

**Comment by cxrodgers** [comment]
just to comment that I also had this issue and fixing the path in '_bdvdataset_0.xml', '_sources.json' 'project.qpproj' was not sufficient. I did `grep OLDPATH -r .` and found that the old path was also encoded in all of the hidden files that end in *.bfmemo alongside the raw images in the QuPath project directory. I deleted them and when I opened ABBA again, it regenerated these hidden files (which takes a while) but then it worked. 

While debugging this, I also changed it in the server.json file corresponding to every single image, but not sure if this was necessary or not.

hope this helps anyone else out there with the same problem!

**Comment by NicoKiaru** [comment]
@cxrodgers damned, well played!

@dgault, is there a way to remove the encoded absolute file path in bfmemo files ? Otherwise moving the files away can create issues. I always assumed the bfmemo files had to be next to the original files, and that changing their location together was safe. Or could the bfmemo files be regenerated if they discover that their absolute path has been changed ?

I can write an issue or an image.sc forum post, which one would you prefer ?

**Comment by NicoKiaru** [comment]
> One last thing, do you have any advice about registering the two-photon
mouse brain atlas images with the apline and spline? The images seem to not
register extremely well, with the edges poking around the whole sides and
the centre/split between hemispheres not being correct. I have tried many
combinations of control points and mm but find that only 15,15 is best.

@mmower2000 if you have some sample images to share, open a post at forum.image.sc. Maybe people will have some ideas. My ideal scenario regarding ABBA is that I, (or even better, someone else) add a fancy versatile deep learning registration plugin to ABBA for the in plane registration which is a bit lacking at the moment.

But I don't have the time to work on this now.

**Comment by mmower2000** [comment]
Hi Nicolas,

Yes that is fair enough. Thank you so much for your help, you have been
great! If you would like me to leave a review anywhere or anything of the
sort just let me know.

Thanks again,

Matthew

**Comment by NicoKiaru** [comment]
Tagging this issue to add its content in the documentation

**Comment by dgault** [comment]
> @dgault, is there a way to remove the encoded absolute file path in bfmemo files ? Otherwise moving the files away can create issues. I always assumed the bfmemo files had to be next to the original files, and that changing their location together was safe. Or could the bfmemo files be regenerated if they discover that their absolute path has been changed ?

This will have to be fixed at the reader level within Bio-Formats, I have opened an issue for the BDVReader specifically, though you may see similar issues with other formats also. https://github.com/ome/bioformats/issues/3957

After the reader has been updated it will mean having the regenerate the existing memo files.

**Comment by NicoKiaru** [comment]
Thanks!

>  I have opened an issue for the BDVReader specifically, though you may see similar issues with other formats also

Indeed, I observed this behaviour for tiffs files

**Comment by NicoKiaru** [comment]
Consider removing memoization or handling a bit better the issue.

**Comment by NicoKiaru** [comment]
This issue is related to a request in bigdataviewer image loader (https://github.com/BIOP/bigdataviewer-image-loaders/issues/25)
