### ISSUE TITLE
Annotations in QuPath are overlapping and hard to read

### ISSUE THREAD

**Issue by cxrodgers** [BIOP/ijp-imagetoatlas#156]
Hello, thanks for your hard work on developing this tool! I have completed registration and exported registrations back to the QuPath project. When I load them into QuPath (Extensions > ABBA > Load Atlas Annotations), the region boundaries are displayed, but the text labels are all along the middle of the image and overlapping. Is there a way to get the text label to display on the actual region? Or to have the text label display only when you click on the region? thanks!

screenshot showing the issue: https://www.dropbox.com/s/mmno1pgxif56fx7/Screenshot%20from%202023-02-07%2009-47-12.png?dl=0

**Comment by NicoKiaru** [comment]
So if you split the regions when importing them between left and right, they will be better positioned. 

By default the region name is display at the center of mass of each region, and because the regions are symmetrical, they will be displayed at the center of the section.

Just a few extra useful tips:
- You can press 'n' to disable the display of the name of the region.
- You can use the transparency slider to change the opacity of the regions

> Is there a way to get the text label to display on the actual region?

If you put a low transparency, double-click on a region and have the hierarchy tab activated, you will see in yellow the region selected, and the region selected will be synchronized on the hierarchy tab:

![image](https://user-images.githubusercontent.com/20223054/217290603-1d57b2fe-7794-4643-b39c-fe875170d38a.png)

(here: LSr) maybe that's an okayish workaround ?

**Comment by cxrodgers** [comment]
Wonderful, thanks so much!

**Comment by NicoKiaru** [comment]
reopening: this should be in the documentation
