### ISSUE TITLE
"Load atlas annotations" only loads one annotation

### ISSUE THREAD

**Issue by Rodgers-PAC-Lab** [BIOP/ijp-imagetoatlas#158]
Hello, I have exported ABBA registration results using "Export Regions to QuPath Project". I can see that the RoiSet.zip, ABBA-Transform.json, and Allen Brain Ontology show up in the data folders for each slice in the QuPath project. However, when I load the annotations in QuPath using "Extensions" > "ABBA" > "Load Atlas Annotations", only one single brain region loads. 

In the terminal, it prints something like "qupath.ext.biop.abba.AtlastTools - Loading 255 Atlas Regions". But only one is displayed, and if I go to the "Hierarchy" tab, there is only 2 objects listed under Root. I don't see any other error messages displayed anywhere. Could someone please give me a tip as to how to debug this? Thanks!

**Comment by cxrodgers** [comment]
Doing a `git pull` in my `qupath` directory and rebuilding it seems to have fixed this! Not sure why -- I was already on 0.4.3-SNAPSHOT, but maybe there were some recent changes.

**Comment by NicoKiaru** [comment]
Pretty weird...

I guess you mean 0.4.3-SNAPSHOT of QuPath ?

**Comment by cxrodgers** [comment]
Yes, I built QuPath from the github version as of a few weeks ago. In the last few days, it's been warning me that a new version is available (I guess because you all released the new version), and I *think* that might be when the problem started (although I'm not sure, and can't understand why the availability of a new version would change anything). Regardless, I pulled from github, built again, and now it works! Maybe it just needed to be rebuilt for some reason unrelated to the new version.
