### ISSUE TITLE
BigWarp 9.0.0 coming

### ISSUE THREAD

**Issue by bogovicj** [BIOP/ijp-imagetoatlas#177]
Hi @NicoKiaru ,

It's been on the way for awhile, but I will make a new major release of BigWarp soon:
https://github.com/saalfeldlab/bigwarp/pull/163

While there are lots of changes, most of the high-level API is still the same. I just tried building this repo with the development version, and it compiled without a problem.

Please let me know how I can help, and if there are other repos that might need testing.
(I'll be able to test building code, but won't be very helpful in testing functionality).

**Comment by NicoKiaru** [comment]
Thanks for warning! I saw a big PR on your repo indeed, this looks great!

Do you have a potential release date ?

Side note: I saw some commits about transform serialization. Is it something I should adopt ? Are there some demo  somewhere ? Cheers

**Comment by bogovicj** [comment]
>  I saw some commits about transform serialization. Is it something I should adopt ? 

It would be great if you could eventually adopt the transform serialization :heart: 

> Are there some demo somewhere ?

Exactly. My next job is to document and make examples for this stuff.  I can let you know when that's ready, and I'd value your feedback!

**Comment by bogovicj** [comment]
I released bigwarp-9.0.0 earlier this week.
https://github.com/saalfeldlab/bigwarp/releases/tag/bigwarp_fiji-9.0.0

It won't go into Fiji yet though - I want to wait until we're confident this repo and whatever other dependencies work with it.  So when you have some time, please give it a try.  As I said, compilation was smooth, so I'm hopeful that the functionality won't cause many problems - and I will be happy to help figure out any issues that arise.

p.s. There are a couple bugs I found and fixed already (of course), so there will be a 9.0.1 soon, and it should include anything we find while testing integration.

Thanks!

**Comment by NicoKiaru** [comment]
Hi @bogovicj ,

I gave a try in the downstream repo bigdataviewer-playground, which is the one used in this repo.

There's a bigwarp-9 branch,

https://github.com/bigdataviewer/bigdataviewer-playground/tree/bigwarp-9

and two self-contained demos for BigWarp:

* https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/test/src/sc/fiji/bdvpg/BigWarp2DTest.java
* https://github.com/bigdataviewer/bigdataviewer-playground/blob/master/src/test/src/sc/fiji/bdvpg/BigWarpDemo.java

Unfortunately, so far, none are working. For BigWarp2DTest I get this error:

```
Exception in thread "main" java.lang.NullPointerException
	at bigwarp.BigWarpData.isMoving(BigWarpData.java:224)
	at bigwarp.BigWarp.createMovingTargetGroups(BigWarp.java:969)
	at bigwarp.BigWarp.initialize(BigWarp.java:824)
	at bigwarp.BigWarp.<init>(BigWarp.java:666)
	at bigwarp.BigWarp.<init>(BigWarp.java:386)
	at sc.fiji.bdvpg.BigWarp2DTest.run(BigWarp2DTest.java:67)
	at sc.fiji.bdvpg.BigWarp2DTest.main(BigWarp2DTest.java:54)
```

and for BigWarpDemo, I get a weird BDV error, probably happening at the initialisation. Then the deformation live update is not working anymore.

If you want to know what's the expected behaviour you can checkout the master branch.

Would you have time to have a look ? If that's easier maybe we can have a quick check together in zoom ?

Cheers

**Comment by bogovicj** [comment]
Thanks @NicoKiaru ! 

I'll have a look soon, and if I'm confused we'll arrange for a zoom talk.

**Comment by bogovicj** [comment]
Looked to me like both of those issues needed fixes in BW, and the BdvPlayground stuff should be fine as is. [One fix](https://github.com/saalfeldlab/bigwarp/commit/8f9a365b08dea711caa39ef041b1bad9af04a8cf) for `BigWarpDemo`, and [another fix](https://github.com/saalfeldlab/bigwarp/commit/45c66049b5d4eb7cb328ebaf8f540cefa4aa7489) for `BigWarp2DTest`

**Comment by NicoKiaru** [comment]
Thanks!

There's a little weird issue:
* in BigWarpDemo, if you press 'f' to display the fused image, it won't be displayed. You need to click 'active' in the Source tab:
![image](https://github.com/BIOP/ijp-imagetoatlas/assets/20223054/f05f1165-44b6-4e22-af3c-8593ec89ed9e)

I'm not sure but I think this behaviour was different before.

Otherwise, all good, as long as I update to pom-scijava 37.

**Comment by bogovicj** [comment]
Good catch - I missed that. [Fixed it!](https://github.com/saalfeldlab/bigwarp/commit/0c54596201c052ce2c71011948bddc207f2f51b1)

**Comment by NicoKiaru** [comment]
Mostly done, one thing left, it's https://github.com/BIOP/ijp-imagetoatlas/issues/195

This is a functionality that's here for performance only, so I'll move on anyway
