### ISSUE TITLE
CZI not working

### ISSUE THREAD

**Issue by Theresa-S** [BIOP/ijp-imagetoatlas#78]
I'm not sure if this is still relevant, but you mention on your webpage "CZI, NDPI, OME-TIFF should work perfectly. Let us know if that’s the case in practice and we’ll update the list."

I just tried with .czi (Slide Scanner data) and the import didn't work, but gave the following error message:

![ABBA_error-message](https://user-images.githubusercontent.com/61883896/123405872-8fe15d00-d5aa-11eb-923c-621e59559bc4.PNG)

![grafik](https://user-images.githubusercontent.com/61883896/123406922-b358d780-d5ab-11eb-94b8-877376533155.png)

In the image containing folder one BFMEMO file was created for the first image. I'm not sure if my PC is just not powerful enough to open the images. If you think this is the problem, I can retry it on a workstation.

In case you're interested in whole-brain slide scanner images for testing, we published a pretty huge data set open access: https://rodare.hzdr.de/record/915 

On a final note, I also tested .mrxs files. I didn't expect it to work and can confirm that nothing happens :-)

**Comment by NicoKiaru** [comment]
Hello @Theresa-S !

Thanks for trying ABBA and for the feedback!

 Yes, maybe I was a bit too optimistic with CZI ;-), but normally it should work : you can retry by checking `split RGB channels` when you import the dataset. If you confirm that it works, I'll update the documentation accordingly.

![image](https://user-images.githubusercontent.com/20223054/123410134-3f203300-d5af-11eb-9523-13e455ba973d.png)

16 bits rgb channels are handled by splitting them as a 3 channels image. 

The dataset you shared is awesome, I wanted to try it, but I just have a hard time figuring out which files I need to download to get a czi example, because everything is splitted in block of 17Gb? Should I download everything ? Or can I open a subset ?

**Comment by Theresa-S** [comment]
Ah, yes that's one problem with the repository. You need to download all 17 GB chunks of the histology data from one mouse, put them IN THE SAME FOLDER and only then the unzipping works. I would recommend the mice C3H_M8 or B6_M10, because those were the untreated controls.

Next time I'm at the bioimage workstation I will try again. I think I was too optimistic with my PC :-)

**Comment by NicoKiaru** [comment]
It should work with your PC, normally there's no need for a big workstation - it's qupath like.

But if you don't check `Split RGB channels` if will not work with 16 bits RGB images, neither on your laptop, nor on the biggest workstation you have.

**Comment by NicoKiaru** [comment]
![cziread_smaller](https://user-images.githubusercontent.com/20223054/123451152-bc629c80-d5dd-11eb-9fb7-0a3cd279ad6f.gif)


I tried with the dataset you mentioned, and it works well with czi (see gif).


But thanks to you, I realized that I messed the 'horizontal' slicing : it gives the same result as sagittal. I need to fix this otherwise you wont' be able to align anything

**Comment by NicoKiaru** [comment]
Ok, the other is also fixed, if you update fiji, you can now slice the atlas horizontally, as in your dataset ( which is really awesome, I should have overcome my fear of downloading it before! )
